x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "10"

networks:
  meedu-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.11.10.0/24

volumes:
  data_mysql:
  data_redis:
  data_meilisearch:
  conf_mysql:

services:
  meedu:
    image: registry.cn-hangzhou.aliyuncs.com/meedu/light:4.9.10
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - QUEUE_DRIVER=${QUEUE_DRIVER}
      - APP_KEY=${APP_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - MEILISEARCH_HOST=${MEILISEARCH_HOST}
      - MEILISEARCH_KEY=${MEILISEARCH_KEY}
    ports:
      - 8000:8000
      - 8100:8100
      - 8200:8200
      - 8300:8300
    networks:
      - meedu-network
    depends_on:
      - mysql
      - redis
    logging: *default-logging

  redis:
    image: registry.cn-hangzhou.aliyuncs.com/hzbs/redis:7.0.12
    restart: always
    volumes:
      - data_redis:/data
    # ports:
    #   - 6379:6379
    networks:
      - meedu-network
    logging: *default-logging

  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/hzbs/mysql:8.1
    restart: always
    environment:
      - MYSQL_DATABASE=meedu
      - MYSQL_ROOT_PASSWORD=meeduxyz
    volumes:
      - data_mysql:/var/lib/mysql
      - conf_mysql:/etc/mysql/conf.d
    # ports:
    #   - 3306:3306
    networks:
      - meedu-network
    logging: *default-logging
  
  meilisearch:
    image: registry.cn-hangzhou.aliyuncs.com/hzbs/meilisearch:0.24.0
    restart: always
    volumes:
      - data_meilisearch:/meili_data
    # ports:
    #   - 7700:7700
    networks:
      - meedu-network
    logging: *default-logging