version: '3.1'

services:
  php:
    container_name: "meedu-php"
#    build:
#      context: ./docker
    image: registry.cn-hangzhou.aliyuncs.com/xiaoteng/meedu-php:v1
    volumes:
      - ./:/var/www/html/
    restart: always
    networks:
      - meedu-net

  mysql:
    container_name: "meedu-mysql"
    image: daocloud.io/mysql:5.7
#    ports:
#      - "3306:3306"
    volumes:
      - ./docker/mysql/logs:/logs/:rw
      - ./docker/mysql/data:/var/lib/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meedu
    restart: always
    networks:
        - meedu-net

  nginx:
    container_name: "meedu-nginx"
    image: daocloud.io/nginx:1.15.7
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html/:rw
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/:rw
      - ./docker/nginx/logs:/var/log/nginx/:rw
      - ./docker/nginx/ssl:/etc/nginx/ssl
    restart: always
    networks:
      - meedu-net

networks:
  meedu-net:
    external: true
